baseURL = 'https://blogs.wuvikr.top/'
locale = 'en-us'
title = "维克的博客"
theme = "PaperMod"

# 全局参数
[params]
  # 文章显示目录
  ShowToc = true
  # 目录默认展开
  TocOpen = true

[params.analytics]
  [params.analytics.umami]
    enable = true
    scriptUrl = "https://cloud.umami.is/script.js"
    websiteId = "01c1c49a-5929-4c1b-99cc-3d7ae8a072dc"

